export const homeObjOne = {
    lightBg: false,
    primary: false,
    imgStart: '',
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: 'Get Started',
    description: 'A simple message board for keyboard enthusiasts.',
    headline: 'Best place to chat about keyboards',
    lightText: true,
    topLine: 'Cat Fat',
    img: require('../../images/svg-1.svg').default,
    alt: 'Image',
    start: '',
}

export const homeObjTwo = {
    lightBg: true,
    primary: false,
    imgStart: 'start',
    lightTopLine: false,
    lightTextDesc: false,
    buttonLabel: 'Get Started',
    description: 'A simple message board for keyboard enthusiasts.',
    headline: 'Best place to chat about keyboards',
    lightText: false,
    topLine: 'Cat Fat',
    img: require('../../images/jpg-1.jpg').default,
    alt: 'Image',
    start: 'true',
}

export const homeObjThree = {
    lightBg: false,
    primary: false,
    imgStart: '',
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: 'Check it out',
    description: 'Not interested in keyboards? check out our general page.',
    headline: 'General Forum',
    lightText: true,
    topLine: 'Cat Fat',
    img: require('../../images/svg-2.svg').default,
    alt: 'Image',
    start: '',
}

export const homeObjFour = {
    lightBg: false,
    primary: false,
    imgStart: 'start',
    lightTopLine: true,
    lightTextDesc: true,
    buttonLabel: 'Get Started',
    description: 'A simple message board for keyboard enthusiasts.',
    headline: 'Best place to chat about keyboards',
    lightText: true,
    topLine: 'Cat Fat',
    img: require('../../images/svg-3.svg').default,
    alt: 'Image',
    start: 'start',
}